server:
  port: ${SERVER_PORT}
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-binding-errors: always
    include-message: on_param
    include-path: always
  tomcat:
    resource:
      allow-caching: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
#  elasticsearch:
#    uris: ${ELASTIC_URI}
#    username: ${ELASTIC_USERNAME}
#    password: ${ELASTIC_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true
  aop:
    auto: true
  rabbitmq:
      host: ${RABBIT_MQ_HOST}
      port: ${RABBIT_MQ_PORT}
      listener:
        direct:
          acknowledge-mode: manual
      password: ${RABBIT_MQ_PASSWORD}
      username: ${RABBIT_MQ_USERNAME}



  mail:
   host: ${MAIL_HOST}
   port: ${MAIL_PORT}
   username: ${MAIL_USERNAME}
   password: ${MAIL_PASSWORD}
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
       transport:
         protocol: smtp

  batch:
    job:
      enabled: true

  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      script: ${REDIS_SCRIPT}

  cache:
    type: redis
    redis:
      time-to-live: 5


  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
    execution:
      shutdown:
        await-termination: true
      thread-name-prefix: jassm-jobs

  jackson:
    date-format: java.text.SimpleDateFormat
  mvc:
    async:
      request-timeout: 5
  servlet:
    multipart:
      enabled: true

logging:
  level:
    web: info
    sql: info
    root: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
stripe:
  secret:
    api-key: ${STRIPE_API_KEY}
  account:
    key: ${STRIPE_ACCOUNT_KEY}
#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_UI_PATH}
#open-api:
#  contact:
#    name: ${OPEN_API_CONTACT_NAME}
#    email: ${MAIL_USERNAME}
#  info:
#    title: ${OPEN_API_CONTACT_TITLE}
#    version: ${OPEN_API_CONTACT_VERSION}
#    description: ${OPEN_API_CONTACT_DESCRIPTION}
#  server:
#    description: ${OPEN_API_SERVER_DESCRIPTION}

order:
  discount:
    value: 10
  limit:
    value: 5
rabbitMq:
  queueName: ${RABBIT_MQ_QUEUE_NAME}
  topicExchangeName: ${RABBIT_MQ_TOPIC_NAME}
  routingKey: ${RABBIT_MQ_ROUTING_KEY}
  directExchange: ${RABBIT_MQ_DIRECT_EXCHANGE}
  ttl: ${RABBIT_TTL}
  headerName: ${RABBIT_HEADER_NAME}


