server:
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-binding-errors: always
    include-message: on_param
    include-path: always
    path: /error
    whitelabel:
      enabled: true
  tomcat:
    resource:
      allow-caching: true
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  web:
    resources:
      static-locations: classpath:/static/
  lifecycle:
    timeout-per-shutdown-phase: 20s
  #  elasticsearch:
#    uris: ${ELASTIC_URI}
#    username: ${ELASTIC_USERNAME}
#    password: ${ELASTIC_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true
  aop:
    auto: true
  rabbitmq:
      host: ${RABBIT_HOST}
      port: ${RABBIT_PORT}
      listener:
        direct:
          acknowledge-mode: ${RABBIT_ACK_MODE}
      password: ${RABBIT_PASSWORD}
      username: ${RABBIT_USERNAME}



#  mail:
#   host: ${MAIL_HOST}
#   port: ${MAIL_PORT}
#   username: ${MAIL_USERNAME}
#   password: ${MAIL_PASSWORD}
#   properties:
#     mail:
#       smtp:
#         auth: true
#         starttls:
#           enable: true
#       transport:
#         protocol: smtp

  batch:
    job:
      enabled: true


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL}
      cache-null-values: false
      use-key-prefix: true
      enable-statistics: true

  validation:
    method:
      adapt-constraint-violations: true
  main:
    lazy-initialization: true

  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
    execution:
      shutdown:
        await-termination: true
      thread-name-prefix: ${THREAD_NAME_PREFIX}

  jackson:
    date-format: ${JACKSON_DATE_FORMAT}
  mvc:
    async:
      request-timeout: 5
  servlet:
    multipart:
      enabled: true

logging:
  level:
    web: ${LOGGING_WEB_TYPE}
    sql: ${LOGGING_SQL_TYPE}
    root: ${LOGGING_ROOT_TYPE}
  pattern:
    console: ${LOGGING_PATTERN}
stripe:
  secret:
    api-key: ${STRIPE_API_KEY}
  account:
    key: ${STRIPE_ACCOUNT_KEY}
springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}
open-api:
  contact:
    name: ${SWAGGER_OPEN_API_CONTACT_NAME}
    email: ${SWAGGER_OPEN_API_CONTACT_EMAIL}
  info:
    title: ${SWAGGER_OPEN_API_INFO_TITLE}
    version: ${SWAGGER_OPEN_API_INFO_VERSION}
    description: ${SWAGGER_OPEN_API_CONTACT_DESCRIPTION}
  server:
    description: ${SWAGGER_OPEN_API_SERVER_DESCRIPTION}

order:
  discount:
    value: ${ORDER_DISCOUNT_VALUE}
  limit:
    value: ${ORDER_LIMIT_VALUE}
rabbitMq:
  queueName: ${ORDER_LIMIT_VALUE}
  topicExchangeName: ${RABBIT_TOPIC_EXCHANGE_NAME}
  routingKey: ${RABBIT_ROUTING_KEY}
  directExchange: ${RABBIT_DIRECTEXCHANGE}
  ttl: ${RABBIT_QUEUE_TTL}
  headerName: ${RABBIT_HEADER_NAME}
s3:
  region: ${S3_REGION}
  accessKey: ${S3_ACCESSKEY}
  secretKey: ${S3_SECRET_KEY}



