server:
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-binding-errors: always
    include-message: on_param
    include-path: always
    path: /error
    whitelabel:
      enabled: true
  tomcat:
    resource:
      allow-caching: true
  port: 3000
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: daniilnovikov
    password: demo2228
    url: jdbc:postgresql://localhost:5432/postgres
  web:
    resources:
      static-locations: classpath:/static/
  #  elasticsearch:
#    uris: ${ELASTIC_URI}
#    username: ${ELASTIC_USERNAME}
#    password: ${ELASTIC_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true
  aop:
    auto: true
  rabbitmq:
      host: localhost
      port: 5672
      listener:
        direct:
          acknowledge-mode: manual
      password: guest
      username: guest



#  mail:
#   host: ${MAIL_HOST}
#   port: ${MAIL_PORT}
#   username: ${MAIL_USERNAME}
#   password: ${MAIL_PASSWORD}
#   properties:
#     mail:
#       smtp:
#         auth: true
#         starttls:
#           enable: true
#       transport:
#         protocol: smtp

  batch:
    job:
      enabled: true


  data:
    redis:
      host: localhost
      port: 6379
      script:


  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false
      use-key-prefix: true
      enable-statistics: true

  validation:
    method:
      adapt-constraint-violations: true
  main:
    lazy-initialization: true

  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
    execution:
      shutdown:
        await-termination: true
      thread-name-prefix: jassm-jobs

  jackson:
    date-format: java.text.SimpleDateFormat
  mvc:
    async:
      request-timeout: 5
  servlet:
    multipart:
      enabled: true

logging:
  level:
    web: info
    sql: info
    root: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
stripe:
  secret:
    api-key: asdfr90q23wera0-d-ase0dr-23q4ew9
  account:
    key: asdfr90q23wera0-d-ase0dr-23q4ew900
springdoc:
  swagger-ui:
    path: /swagger-ui.html
open-api:
  contact:
    name: dnNvk
    email: ololorash2001@mail.ru
  info:
    title: Jassm
    version: 1
    description: DarkNet-Marketplace
  server:
    description: Welcome to the club, Boddy

order:
  discount:
    value: 10
  limit:
    value: 5
rabbitMq:
  queueName: Jassm
  topicExchangeName: Jassm-Topic-Exchange
  routingKey: 4389wr8430-w49320
  directExchange: Jassm-Direct-Exchange
  ttl: 60
  headerName: rabbit-header
s3:
  region: RU
  accessKey: 1320920-423-0qw4
  secretKey: -304-3204230430953095



